### ISSUE TITLE
Visual Studio 2017 compilation error

### ISSUE THREAD

**Issue by Gutherz** [atilaneves/premock#5]
This new code from last commit causes error on visual studio 2017

> #if __cplusplus < 201703L
> namespace std {
> template<typename... Ts> struct make_void { typedef void type;};
> template<typename... Ts> using void_t = typename make_void<Ts...>::type;
> }

> E2626	alias template type "std::make_void<Ts...>::type" is incompatible with the previous type of "void" in the redeclaration of alias template "std::void_t" (declared at line 179 of "c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\type_traits")

Trying to comment this line causes different error

> C2679	binary '=': no operator found which takes a right-hand operand of type 'Test_SDL_Strings_ConcatStringsTest_Test::TestBody::<lambda_9427c55ed5f3ba2f27f9d5a3c27cb397>' (or there is no acceptable conversion)

**Comment by atilaneves** [comment]
I don't have VS 2017, so I can't reproduce this.

I copied that implementation of `void_t` from either gcc or clang before C++17 was approved. I'd suggest going to the relevant VS 2017 header, copying it here and `#ifdef`ing the whole thing for Windows.

**Comment by Bu11etmagnet** [comment]
Which language compatibility flag did you use? 
(I don't have VS 2017, but from the error message it seems to me that it (or its STL) makes void_t available even in C++14 or C++11 mode, confusing premock).

**Comment by marmidr** [comment]
This is not only VS problem.
I have the same issue on Ubuntu after updating g++ from 5.4 to 7.3

`premock.hpp:189:72: error: conflicting declaration of template ‘template<class ... Ts> using void_t = typename std::make_void::type’
 template<typename... Ts> using void_t = typename make_void<Ts...>::type;`
I compile my tests in C++14 mode

I changed the guard from
`#if __cplusplus < 201703L`
to
`#if __cplusplus <= 201103L`
and it helped.

**Comment by atilaneves** [comment]
@mmidor I can't reproduce that on Linux with gcc 8.2.0 with -std=c++14.

**Comment by atilaneves** [comment]
I hate Windows: https://blogs.msdn.microsoft.com/vcblog/2018/04/09/msvc-now-correctly-reports-__cplusplus/

Sigh.

**Comment by nyquist-h** [comment]
> @mmidor I can't reproduce that on Linux with gcc 8.2.0 with -std=c++14.

Sorry for bumping the old thread, but I am having a similar problem as @mmidor. gcc 8.2.0 uses the -std=gnu14 as default if not otherwise specified. The problem is that void_t was implemented in gcc as an language extension before it was standardized in c++17. If using default gcc options, premock won't compile. An solution would be changing ` if __cplusplus < 201703L` to` ifndef __cpp_lib_void_t `. This works for clang (starting from v.3.5) and gcc (starting from v.4.9).

**Comment by atilaneves** [comment]
@nyquist-h Since I can't reproduce this, please submit a PR.
